### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'icon')

### ISSUE THREAD

**Issue by marx-freedom** [diplodoc-platform/cli#1125]
### Package version

4.54.6

### Node version

v22.14.0

### What steps will reproduce the bug?

Dockerfile:
```
FROM node:22

RUN npm i @diplodoc/cli@4.54.6 -g && \
npm i @diplodoc/transform -g && \
npm i -g embedme && \
npm i -g changie && \
npm cache clean --force
```

Пока не понятно как воспроизвести, никаких icon/logo нигде не указываем. Относительно обычная документация. На одном единственном файле не воспроизводится.

toc выглядит примерно так:

```
title: some text {{ version }}
href: index.yaml
navigation:
  header:
    leftItems:
      - text: some test
        type: "link"
        url: "https://gitlab.example/pages/"
items:
  - name: title1
    expanded: false
    href: user/user_index.yaml
    items:
      - include: { mode: link, path: user/user_toc.yaml }
  - name: title2 
    href: kdoc/kdoc_index.yaml
  - name: title3
    href: dev/dev_index.yaml
    items:
      - include: { mode: link, path: dev/dev_toc.yaml }
```

### What is the expected behavior?

Обычное поведение, как в прошлой версии.

### What do you see instead?

"Белый экран" вместо документации, в консоли браузера ошибка

```
react.js:2 TypeError: Cannot read properties of undefined (reading 'icon')
    at app.js:1:11778
    at Object.useMemo (react.js:2:66633)
    at n.useMemo (react.js:2:135151)
    at app.js:1:11515
    at De (app.js:1:11943)
    at hu (react.js:2:60335)
    at Ei (react.js:2:119276)
    at bs (react.js:2:108528)
    at vs (react.js:2:108456)
    at gs (react.js:2:108319)
co  @  react.js:2
```

### Additional information

На 4.53.15 все ок, на 4.54.6 и более новых версиях - ошибка. Проверил последние патч версии каждого минорного релиза, но конечно же обновиться хотелось бы просто на последний.
