### ISSUE TITLE
TOC including doesn't work at the same level

### ISSUE THREAD

**Issue by vsesh** [diplodoc-platform/cli#789]
I have this file structure:
```
- toc.yaml
- toc_test.yaml 
- page1.md
```

`toc.yaml`:
```
title: test
items:
  - name: Test
    href: ./toc_test.yaml
 ```
 
 `toc_test.yaml`:
```
items:
  - name: Test page
    href: ./page1.md
 ```
 
 And I received this error in the end: 
 ```
 ERR Link is unreachable: ./page1.md in /toc_test.yaml
 ```
 
 Everything works fine if you place `sub_toc.yaml` and `page1.md` in some subfolder.
