### ISSUE TITLE
--single-page mode generates single-page.html with index page in the end

### ISSUE THREAD

**Issue by bongiozzo** [diplodoc-platform/cli#825]
toc.yaml

```
title: Main Title
href: index.md
items:
  - name: Part 1
    expanded: true
    items: 
    - name: Title 1
      href: title1.md
    ....
```

npx -- @diplodoc/cli@latest -i docs -o docs-html --single-page

index.html was generated Ok (contains correct Navigation and index.md text)

but

single-page.html was generated starting from title1.md and index.md is in the end of single page.
