### ISSUE TITLE
Отсутствие url иконки ломает отображение

### ISSUE THREAD

**Issue by dyakovri** [diplodoc-platform/cli#921]
Если в toc.yml прописать лого без иконки
```
navigation:
  logo:
    text: "Some text"
    url: "https://some.net"
```

Билд происходит успешно, но открытие страницы сопровождается js ошибкой выставления атрибута alt иконке и пустой страницей

Воспроизводится на последней актуальной версии. Не воспроизводится на версии 4.35.1 и ниже
